name: Build OFE (Windows)
on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
       pip install --upgrade pip
       pip install pyAesCrypt customtkinter Pillow requests nuitka
    - name: Build with Nuitka
      run: |
        python -m nuitka --onefile --windows-console-mode=disable --include-data-dir=Enc/Assets/=Assets --windows-uac-admin --enable-plugin=tk-inter --windows-icon-from-ico=Enc/Assets/Icon.ico --assume-yes-for-downloads OpenFileEncryptor.py
    - name: Upload built binary
      uses: actions/upload-artifact@v4
      with:
        name: OpenFileEncryptor
        path: OpenFileEncryptor.exe
